services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  dashboard:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OCR_ASYNC=1
    depends_on:
      - redis
    ports:
      - "5000:5000"

  worker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app/src
    depends_on:
      - redis
    command: ["sh", "-c", "rq worker -u \"$REDIS_URL\" ocr"]
